version: "3"

services:
  db:
    build: ./mysql_with_dump
    volumes:
      - ./mysql_with_dump/mysqldata:/var/lib/mysql
    networks:
      - backend

  elasticsearch:
    image: elasticsearch:6.7.0
    ports:
      - 9200:9200
    volumes:
      - ./elasticsearch/esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    networks:
      - backend

  kibana:
    image: kibana:6.7.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - backend

  logstash:
    build: ./logstash
    depends_on:
      - elasticsearch
      - db
    #environment:
    #WAIT_HOSTS: db:3306
    env_file:
      - .env
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    networks:
      - backend

networks:
  backend:
